### ISSUE TITLE
Predicting edge directions

### ISSUE THREAD

**Issue by nicholasdomene** [LarremoreLab/SpringRank#2]
In section  "Predicting edge directions", there is a description on how to calculate the probability of an edge being directed from i to j as a sigmoid function with parameters beta and the rank difference between nodes i and j. Should it be implemented within the package? I could help with that, since it should be a fairly straightforward implementation.

**Comment by nicholasdomene** [comment]
Looks likes it is already implemented inside function `eqs39` as it is used to find the optimal beta value. Also might be worthwhile noting somewhere that the beta is being optimized for the "log likelihood of generating the directed edges given their existence", so sigma_L, and not "average probability assigned to the correct direction of an edge", so sigma_A.

**Comment by dblarremore** [comment]
Added in https://github.com/LarremoreLab/SpringRank/commit/093da4935529c69ba88a269fe2250e111a189230
